### ISSUE TITLE
Testing Question

### ISSUE THREAD

**Issue by blsmit5728** [z4r/python-trakt#3]
I have been working on adding more to your API and was trying to figure out the whole testing method you have implemented. I tried adding a method for user/list to the tests but it kept failing the json parsing (I added a list.json under responses/user/ folder). I'd like to contribute to making this API more robust, but I don't want to issue a pull request until I can run the same unit tests you have implemented. Thanks.
PS: didn;t know how to contact you, figured this was the easiest.

**Comment by z4r** [comment]
Hi @blsmit5728,
thx for your interest.
I suggest you to commit something on your fork so i could understand what you're misunderstanding. :)

Anyway you can contact me on skype: z4erre

cu

**Comment by blsmit5728** [comment]
There should be a couple commits there from today on my fork. No skype, sorry

**Comment by z4r** [comment]
trakt/api.py    

``` python

class User(AbstractApi):
    @classmethod
    def list(cls, user, slug):
        """
        returns the Users list that was requested
        """
        return cls._get('user/list', user, slug)

    @classmethod
    def lists(cls, user):
        """
        returns the availble lists for a user
        """
        return cls._get('user/lists', user)

    @classmethod
    def profile(cls, user):
        return cls._get('user/profile', user)

    @classmethod
    def progress_collected(cls, user):
        return cls._get('user/progress/collected', user)
```

trakt/tests/test_api.py 

``` python
response = User.list(user='justin', slug='Example')
```

and a missing comma in `trakt/tests/response/user/list.json` around line 88

**Comment by z4r** [comment]
If you need any help re open this issue

**Comment by blsmit5728** [comment]
I think I'm good, i have a few changes if you'd like me to up stream them I
can. I never got around to writing all the tests though.

Sent from my iPhone

On Sep 18, 2014, at 02:07, Andrea de Marco notifications@github.com wrote:

If you need any help re open this issue
