### ISSUE TITLE
Trying to figure out how to reference a TVShow or Movie by IMDB_ID or TVDB_ID

### ISSUE THREAD

**Issue by stampedeboss** [z4r/python-trakt#4]
The documentation states that for TVShows the tvdb_id could be used but I can't seem to figure it out.  There are no examples of this functionality.  I've looked at the code and don't see how it is to be done.

**Comment by z4r** [comment]
Hi @stampedeboss,
as mentioned in trakt.tv API doc

```
title
Either the slug (i.e. the-walking-dead) or TVDB ID. You can get a show's slug by browsing the     website and looking at the URL when on a show summary page.
```

So you can adapt:

``` python
import trakt.tv
trakt.tv.setup(apikey=<YOUR_APIKEY>)
trakt.tv.show.episode('the-walking-dead', 1, 1)
#http://api.trakt.tv/show/episode/summary.json/<YOUR_APIKEY>/the-walking-dead/1/1
```

to

``` python
import trakt.tv
trakt.tv.setup(apikey=<YOUR_APIKEY>)
trakt.tv.show.episode(153021, 1, 1)
#http://api.trakt.tv/show/episode/summary.json/<YOUR_APIKEY>/153021/1/1
```

Anyway if you don't understand some api in particular plz reopen this issue :)

**Comment by stampedeboss** [comment]
I am getting the following error:
aj@happy:~$ python
Python 2.7.3 (default, Feb 27 2014, 19:58:35)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import trakt.tv
> > > trakt.tv.setup(apikey='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: 'module' object has no attribute 'setup'

What have I missed?

On Wed, Jul 23, 2014 at 2:17 AM, Andrea de Marco notifications@github.com
wrote:

> Hi @stampedeboss https://github.com/stampedeboss,
> as mentioned in trakt.tv API doc
> 
> title
> Either the slug (i.e. the-walking-dead) or TVDB ID. You can get a show's slug by browsing the     website and looking at the URL when on a show summary page.
> 
> So you can adapt:
> 
> import trakt.tvtrakt.tv.setup(apikey=<YOUR_APIKEY>)trakt.tv.show.episode('the-walking-dead', 1, 1)#http://api.trakt.tv/show/summary.json/<YOUR_APIKEY>/the-walking-dead
> 
> to
> 
> import trakt.tvtrakt.tv.setup(apikey=<YOUR_APIKEY>)trakt.tv.show.episode(153021, 1, 1)#http://api.trakt.tv/show/summary.json/<YOUR_APIKEY>/153021
> 
> Anyway if you don't understand some api in particular plz reopen this
> issue :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/z4r/python-trakt/issues/4#issuecomment-49840549.

## 

AJ Reynolds

**Comment by z4r** [comment]
This work for me

``` python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import trakt.tv
>>> trakt.tv.setup(apikey='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
```

Could you try with:

``` python
>>> from trakt import tv
>>> tv.setup(apikey='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
```

?
